# Generated by Django 3.1.13 on 2022-01-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='E_email',
        ),
    ]
